[ppp]
mode = "classic"
localPath_tgt = ""
localPath_ppc = ""
visibility_check = false
daily_plan = true
proposalIds = ["S26A-126"]

[qplan]
overhead = "5"
obs_dates = ["2026-05-06", "2026-05-07"]
start_time = ["2026-05-07 00:20:00", "2026-05-08 00:20:00"]
stop_time = ["2026-05-07 05:05:00", "2026-05-08 05:05:00"]

[targetdb.sky]
version = ["20230209"]

[targetdb.fluxstd]
version = "3.5"

[netflow]
cobra_location_group_n = 50
min_sky_targets_per_location = 8
location_group_penalty = 100000000000.0
cobra_safety_margin = 0.1
apply_nir_flag = true

[sfa]
n_sky = 400
n_sky_random = 4000
dot_margin = 1.65
guidestar_mag_min = 12.0
guidestar_mag_max = 22.0
n_fluxstd = 200
fluxstd_mag_max = 19.0
fluxstd_mag_min = 17.0
fluxstd_mag_filter = "g"
good_fluxstd = false
fluxstd_min_prob_f_star = 0.5
fluxstd_min_teff = 5000
fluxstd_max_teff = 8000
filler = true
filler_mag_min = 17.0
filler_mag_max = 99.0
n_fillers_random = 30000
fill_unassign_radius_check = 0.00083
fill_unassign = true
fill_unassign_radius = 0.00694
fill_unassign_gaia_mag = 18.0
fill_unassign_pslId = "S25A-000QF"

[ope]
runName = "test"
n_split_frame = 2

[packages]
config_path = "config_database.toml"

