[packages]
pfs_datamodel_ver = "w.2026.06"
pfs_utils_ver = "w.2026.06"
ics_cobraCharmer_ver = "1.5.0"
ics_cobraOps_ver = "v2.0.4"
ets_fiberalloc_ver = "v3.2"
pfs_instdata_ver = "1.8.64"
ets_pointing_ver = "01d572319f84e02cf95dafcb0b9ffd439ef177d4"
pfs_obsproc_planning_ver = "1a4d718"
ets_shuffle_ver = ""
ets_target_database_ver = "834bc2dd6cc20d4f288eb2cbbd605297d29c31ac"
ics_fpsActor_ver = "fcc5728"
spt_operational_database_ver = "9b43c03"
qplan_ver = "v1.1.0"
